name = "secp256k1-kv-db"
main = "src/index.ts"
compatibility_date = "2023-09-14"

[[kv_namespaces]]
binding = "PRIVATE_STORE"
id = "198cd439a1e2498e98c4e70f0aaaa47f"
preview_id = "a6327ec076ba42f589d1791afa537cf5"

